[build]
    publish = "_site"
    command = "npm run build"
    functions = "./src/functions"

[[redirects]]
  from = "/racefactor"
  to = "/pdf/racefactor.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/racefactor/"
  to = "/pdf/racefactor.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/bigtobacco"
  to = "/pdf/big-tobacco-cheat-sheet.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/bigtobacco/"
  to = "/pdf/big-tobacco-cheat-sheet.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/merch"
  to = "https://withac.net/collections/parabola-center-for-law"
  status = 302
  force = false

[[redirects]]
  from = "/merch/"
  to = "https://withac.net/collections/parabola-center-for-law"
  status = 302
  force = false

[[redirects]]
  from = "/peopleoverprofits"
  to = "https://www.eventbrite.com/e/people-over-profits-anti-monopoly-cannabis-reform-crash-course-tickets-893952575217"
  status = 302
  force = false

[[redirects]]
  from = "/peopleoverprofits/"
  to = "https://www.eventbrite.com/e/people-over-profits-anti-monopoly-cannabis-reform-crash-course-tickets-893952575217"
  status = 302
  force = false 