[build]
    publish = "_site"
    command = "npm run build"
    functions = "./src/functions"

[[redirects]]
  from = "/racefactor"
  to = "/pdf/racefactor.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/racefactor/"
  to = "/pdf/racefactor.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/bigtobacco"
  to = "/pdf/big-tobacco-cheat-sheet.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/bigtobacco/"
  to = "/pdf/big-tobacco-cheat-sheet.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/merch"
  to = "https://withac.net/collections/parabola-center-for-law"
  status = 302
  force = false

[[redirects]]
  from = "/merch/"
  to = "https://withac.net/collections/parabola-center-for-law"
  status = 302
  force = false

[[redirects]]
  from = "/peopleoverprofits"
  to = "/crashcourse/"
  status = 302
  force = false

[[redirects]]
  from = "/peopleoverprofits/"
  to = "/crashcourse/"
  status = 302
  force = false

[[redirects]]
  from = "/leadership"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSfpdiFC2ffmT8hhy48Ldp8JoZE4B-aWy4vIHDbt0zgV0eQPug/viewform?usp=sharing&ouid=105905877343898825798"
  status = 302
  force = false

[[redirects]]
  from = "/leadership/"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSfpdiFC2ffmT8hhy48Ldp8JoZE4B-aWy4vIHDbt0zgV0eQPug/viewform?usp=sharing&ouid=105905877343898825798"
  status = 302
  force = false

[[redirects]]
  from = "/2025fellowship"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSfpSr4SQ4OyRPPETc-zrkdoFLBCiIADskOQK9lZfIwDPbXfXw/viewform"
  status = 302
  force = false

[[redirects]]
  from = "/2025fellowship/"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSfpSr4SQ4OyRPPETc-zrkdoFLBCiIADskOQK9lZfIwDPbXfXw/viewform"
  status = 302
  force = false

[[redirects]]
  from = "/survey"
  to = "/pdf/American%20Values%20and%20Beliefs%20About%20Legalization.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/survey/"
  to = "/pdf/American%20Values%20and%20Beliefs%20About%20Legalization.pdf"
  status = 302
  force = false

[[redirects]]
  from = '/longsleeve'
  to = 'https://withac.net/products/parabola-center-black-longsleeve'
  status = 302
  force = false

[[redirects]]
  from = '/longsleeve/'
  to = 'https://withac.net/products/parabola-center-black-longsleeve'
  status = 302
  force = false

[[redirects]]
  from = '/merch'
  to = 'https://withac.net/products/parabola-center-black-longsleeve'
  status = 302
  force = false

[[redirects]]
  from = '/merch/'
  to = 'https://withac.net/products/parabola-center-black-longsleeve'
  status = 302
  force = false

[[redirects]]
  from = '/leadership2026'
  to = 'https://docs.google.com/forms/d/e/1FAIpQLScYKPyLMtKHP5f-6k3RJV0Sbe92oYdO5mWUlRFnRfEeYUgf5Q/viewform?usp=send_form'
  status = 302
  force = false

[[redirects]]
  from = '/leadership2026/'
  to = 'https://docs.google.com/forms/d/e/1FAIpQLScYKPyLMtKHP5f-6k3RJV0Sbe92oYdO5mWUlRFnRfEeYUgf5Q/viewform?usp=send_form'
  status = 302
  force = false

[[redirects]]
  from = "/illinoismarket"
  to = "/pdf/The%20Illusion%20of%20Competition.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/illinoismarket/"
  to = "/pdf/The%20Illusion%20of%20Competition.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/illusion-of-competition"
  to = "/pdf/The%20Illusion%20of%20Competition.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/illusion-of-competition/"
  to = "/pdf/The%20Illusion%20of%20Competition.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/illinoismarkets"
  to = "/pdf/The%20Illusion%20of%20Competition.pdf"
  status = 302
  force = false

[[redirects]]
  from = "/illinoismarkets/"
  to = "/pdf/The%20Illusion%20of%20Competition.pdf"
  status = 302
  force = false
  